{
  "HWYLA" = {
    "src" = "https://minecraft.curseforge.com/projects/hwyla/files/2355186/download";
    "version" = "1.8.5-B19_1.11";
    "title" = "Hwyla";
    "projectID" = 253449;
    "filename" = "Hwyla-1.8.5-B19_1.11.jar";
    "dependencies" = [];
    "encoded" = "Hwyla-1.8.5-B19_1.11.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/HWYLA";
    "type" = "remote";
    "md5" = "5d8055e33b032d0f2a262180a4b633fd";
  };
  "applecore" = {
    "comment" = "Comments are completely optional, but get put in the autogenerated mod list.";
    "projectID" = 224472;
    "title" = "AppleCore";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/applecore";
  };
  "appleskin" = {
    "projectID" = 248787;
    "title" = "AppleSkin";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/appleskin";
  };
  "bagelsmore-the-return" = {
    "projectID" = 248538;
    "title" = "Bagelsmore: The Return";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/bagelsmore-the-return";
  };
  "better-builders-wands" = {
    "src" = "https://minecraft.curseforge.com/projects/better-builders-wands/files/2359682/download";
    "version" = "1.11-0.9.3.194+16eed85";
    "title" = "Better Builder&#x27;s Wands";
    "projectID" = 238403;
    "filename" = "BetterBuildersWands-1.11-0.9.3.194+16eed85.jar";
    "dependencies" = [];
    "encoded" = "BetterBuildersWands-1.11-0.9.3.194%2B16eed85.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/better-builders-wands";
    "type" = "remote";
    "md5" = "c01fbb7648480ae957742d8f648b50ca";
  };
  "blood-magic" = {
    "projectID" = 224791;
    "title" = "Blood Magic ";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/blood-magic";
  };
  "botania" = {
    "projectID" = 225643;
    "title" = "Botania";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/botania";
  };
  "chat-tweaks" = {
    "projectID" = 243506;
    "title" = "Chat Tweaks";
    "type" = "missing";
    "side" = "client";
    "projectPage" = "https://minecraft.curseforge.com/projects/chat-tweaks";
  };
  "chisel" = {
    "projectID" = 235279;
    "title" = "Chisel";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/chisel";
  };
  "chisels-bits" = {
    "src" = "https://minecraft.curseforge.com/projects/chisels-bits/files/2360040/download";
    "version" = "13.6";
    "title" = "Chisels & Bits";
    "projectID" = 231095;
    "filename" = "chiselsandbits-13.6.jar";
    "dependencies" = [];
    "encoded" = "chiselsandbits-13.6.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/chisels-bits";
    "type" = "remote";
    "md5" = "7d7b83157e5a2f4f72a476592b078705";
  };
  "controlling" = {
    "projectID" = 250398;
    "title" = "Controlling";
    "type" = "missing";
    "side" = "client";
    "projectPage" = "https://minecraft.curseforge.com/projects/controlling";
  };
  "cooking-for-blockheads" = {
    "projectID" = 231484;
    "title" = "Cooking for Blockheads";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/cooking-for-blockheads";
  };
  "crafting-tweaks" = {
    "src" = "https://minecraft.curseforge.com/projects/crafting-tweaks/files/2345813/download";
    "version" = "1.11-7.1.1";
    "title" = "Crafting Tweaks";
    "projectID" = 233071;
    "filename" = "CraftingTweaks_1.11-7.1.1.jar";
    "dependencies" = [];
    "encoded" = "CraftingTweaks_1.11-7.1.1.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/crafting-tweaks";
    "type" = "remote";
    "md5" = "b1001493f723d06acaec2dee430c065e";
  };
  "crafttweaker" = {
    "projectID" = 239197;
    "title" = "CraftTweaker";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/crafttweaker";
  };
  "custom-main-menu" = {
    "src" = "https://minecraft.curseforge.com/projects/custom-main-menu/files/2350836/download";
    "version" = "1.11-2.0.3";
    "title" = "Custom Main Menu";
    "projectID" = 226406;
    "filename" = "CustomMainMenu-MC1.11-2.0.3.jar";
    "dependencies" = [];
    "encoded" = "CustomMainMenu-MC1.11-2.0.3.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/custom-main-menu";
    "type" = "remote";
    "side" = "client";
    "md5" = "a04565dd46cd855973a260e824c81aa9";
  };
  "customoregen" = {
    "projectID" = 237130;
    "title" = "CustomOreGen";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/customoregen";
  };
  "cyberware" = {
    "projectID" = 248042;
    "title" = "Cyberware";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/cyberware";
  };
  "dark-utilities" = {
    "projectID" = 242195;
    "title" = "Dark Utilities";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/dark-utilities";
  };
  "default-options" = {
    "src" = "https://minecraft.curseforge.com/projects/default-options/files/2350844/download";
    "version" = "1.11-7.1.1";
    "title" = "Default Options";
    "projectID" = 232131;
    "filename" = "DefaultOptions_1.11-7.1.1.jar";
    "dependencies" = [];
    "encoded" = "DefaultOptions_1.11-7.1.1.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/default-options";
    "type" = "remote";
    "md5" = "0e38056a15d53acc2f5c5539c7d1b011";
  };
  "ding" = {
    "src" = "https://minecraft.curseforge.com/projects/ding/files/2346985/download";
    "version" = "1.11-1.0.1";
    "title" = "Ding";
    "projectID" = 231275;
    "filename" = "Ding-1.11-1.0.1.jar";
    "dependencies" = [];
    "encoded" = "Ding-1.11-1.0.1.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/ding";
    "type" = "remote";
    "md5" = "180f3e920f7ec8963f98713619c0ff3b";
  };
  "embers" = {
    "projectID" = 251918;
    "title" = "Embers";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/embers";
  };
  "ender-io" = {
    "projectID" = 64578;
    "title" = "Ender IO";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/ender-io";
  };
  "flat-colored-blocks" = {
    "src" = "https://minecraft.curseforge.com/projects/flat-colored-blocks/files/2352220/download";
    "version" = "1.11-5.1";
    "title" = "Flat Colored Blocks";
    "projectID" = 238590;
    "filename" = "flatcoloredblocks-mc1.11-5.1.jar";
    "dependencies" = [];
    "encoded" = "flatcoloredblocks-mc1.11-5.1.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/flat-colored-blocks";
    "type" = "remote";
    "md5" = "908309d399ff9fa6e5fbc9164a792c42";
  };
  "forestry" = {
    "projectID" = 59751;
    "title" = "Forestry";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/forestry";
  };
  "immersive-engineering" = {
    "projectID" = 231951;
    "title" = "Immersive Engineering";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/immersive-engineering";
  };
  "integrated-dynamics" = {
    "projectID" = 236307;
    "title" = "Integrated Dynamics";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/integrated-dynamics";
  };
  "integrated-tunnels" = {
    "projectID" = 251389;
    "title" = "Integrated Tunnels";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/integrated-tunnels";
  };
  "inventory-sorter" = {
    "projectID" = 240633;
    "title" = "Inventory Sorter";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/inventory-sorter";
  };
  "iron-backpacks" = {
    "projectID" = 227049;
    "title" = "Iron Backpacks";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/iron-backpacks";
  };
  "iron-chests" = {
    "src" = "https://minecraft.curseforge.com/projects/iron-chests/files/2346667/download";
    "version" = "1.11-7.0.17.799";
    "title" = "Iron Chests";
    "projectID" = 228756;
    "filename" = "ironchest-1.11-7.0.17.799.jar";
    "dependencies" = [];
    "encoded" = "ironchest-1.11-7.0.17.799.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/iron-chests";
    "type" = "remote";
    "md5" = "8464ca19eb477215082a3011799feaad";
  };
  "ivtoolkit" = {
    "src" = "https://minecraft.curseforge.com/projects/ivtoolkit/files/2353302/download";
    "version" = "1.3";
    "title" = "IvToolkit";
    "projectID" = 224535;
    "filename" = "IvToolkit-1.3.jar";
    "dependencies" = [];
    "encoded" = "IvToolkit-1.3.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/ivtoolkit";
    "type" = "remote";
    "md5" = "4b60d727b63da3ad4d11969d54e4f365";
  };
  "just-enough-buttons" = {
    "src" = "https://minecraft.curseforge.com/projects/just-enough-buttons/files/2357014/download";
    "version" = "1.11-1.2";
    "title" = "Just Enough Buttons";
    "projectID" = 248747;
    "filename" = "justenoughbuttons-1.11-1.2.jar";
    "dependencies" = [];
    "encoded" = "justenoughbuttons-1.11-1.2.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/just-enough-buttons";
    "type" = "remote";
    "md5" = "f6f5ef1d76c323358ccaaff216dd39be";
  };
  "just-enough-calculation" = {
    "projectID" = 242223;
    "title" = "Just Enough Calculation";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/just-enough-calculation";
  };
  "just-enough-forestry-bees-jefb" = {
    "projectID" = 247955;
    "title" = "Just Enough Forestry Bees (JEFB)";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/just-enough-forestry-bees-jefb";
  };
  "just-enough-items-jei" = {
    "src" = "https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2357897/download";
    "version" = "1.11-4.1.1.207";
    "title" = "Just Enough Items (JEI)";
    "projectID" = 238222;
    "filename" = "jei_1.11-4.1.1.207.jar";
    "dependencies" = [];
    "encoded" = "jei_1.11-4.1.1.207.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/just-enough-items-jei";
    "type" = "remote";
    "md5" = "041980f44e1297ed4ea004ae2dbabae1";
  };
  "just-enough-resources-jer" = {
    "src" = "https://minecraft.curseforge.com/projects/just-enough-resources-jer/files/2352974/download";
    "version" = "1.11-0.6.1.100";
    "title" = "Just Enough Resources (JER)";
    "projectID" = 240630;
    "filename" = "JustEnoughResources-1.11-0.6.1.100.jar";
    "dependencies" = [238222];
    "encoded" = "JustEnoughResources-1.11-0.6.1.100.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/just-enough-resources-jer";
    "type" = "remote";
    "md5" = "ec7fb2958f2231988ad7f5c35438445f";
  };
  "lantern" = {
    "projectID" = 252997;
    "title" = "Lantern";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/lantern";
  };
  "literal-ascension" = {
    "src" = "https://minecraft.curseforge.com/projects/literal-ascension/files/2360178/download";
    "version" = "1.11-1.0.0.3";
    "title" = "Literal Ascension";
    "projectID" = 253021;
    "filename" = "literalascension-1.11-1.0.0.3.jar";
    "dependencies" = [243298 248453];
    "encoded" = "literalascension-1.11-1.0.0.3.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/literal-ascension";
    "type" = "remote";
    "md5" = "057faf9428816b588a4d925fd4a9e956";
  };
  "llibrary" = {
    "src" = "https://minecraft.curseforge.com/projects/llibrary/files/2349389/download";
    "version" = "1.7.2-1.11";
    "title" = "LLibrary";
    "projectID" = 243298;
    "filename" = "llibrary-1.7.2-1.11.jar";
    "dependencies" = [];
    "encoded" = "llibrary-1.7.2-1.11.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/llibrary";
    "type" = "remote";
    "md5" = "050ea53a3b4aace17db420c1aede38df";
  };
  "modtweaker" = {
    "projectID" = 220954;
    "title" = "ModTweaker";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/modtweaker";
  };
  "more-overlays" = {
    "src" = "https://minecraft.curseforge.com/projects/more-overlays/files/2346640/download";
    "version" = "1.9-mc1.11";
    "title" = "More Overlays";
    "projectID" = 243478;
    "filename" = "moreoverlays-1.9-mc1.11.jar";
    "dependencies" = [];
    "encoded" = "moreoverlays-1.9-mc1.11.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/more-overlays";
    "type" = "remote";
    "md5" = "793c111e426e1682a2c85a3838862770";
  };
  "morph-o-tool" = {
    "projectID" = 245287;
    "title" = "Morph-o-Tool";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/morph-o-tool";
  };
  "mouse-tweaks" = {
    "src" = "https://minecraft.curseforge.com/projects/mouse-tweaks/files/2352926/download";
    "version" = "2.7-mc1.11";
    "title" = "Mouse Tweaks";
    "projectID" = 60089;
    "filename" = "MouseTweaks-2.7-mc1.11.jar";
    "dependencies" = [];
    "encoded" = "MouseTweaks-2.7-mc1.11.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/mouse-tweaks";
    "type" = "remote";
    "md5" = "3a76542ea301cf11aa86ac4e471ecc3f";
  };
  "netherex" = {
    "projectID" = 248039;
    "title" = "NetherEx";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/netherex";
  };
  "opencomputers" = {
    "projectID" = 223008;
    "title" = "OpenComputers";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/opencomputers";
  };
  "portable-crafting" = {
    "projectID" = 240655;
    "title" = "Portable Crafting";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/portable-crafting";
  };
  "quantumstorage" = {
    "projectID" = 235121;
    "title" = "QuantumStorage";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/quantumstorage";
  };
  "quark" = {
    "projectID" = 243121;
    "title" = "Quark";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/quark";
  };
  "railcraft" = {
    "projectID" = 51195;
    "title" = "Railcraft";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/railcraft";
  };
  "realistic-terrain-generation" = {
    "projectID" = 237989;
    "title" = "Realistic Terrain Generation";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/realistic-terrain-generation";
  };
  "reborncore" = {
    "src" = "https://minecraft.curseforge.com/projects/reborncore/files/2357079/download";
    "version" = "1.11-2.11.3.65-universal";
    "title" = "RebornCore";
    "projectID" = 237903;
    "filename" = "RebornCore-1.11-2.11.3.65-universal.jar";
    "dependencies" = [];
    "encoded" = "RebornCore-1.11-2.11.3.65-universal.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/reborncore";
    "type" = "remote";
    "md5" = "6f47519a9325b4284eacf2aa552523a7";
  };
  "recurrent-complex" = {
    "src" = "https://minecraft.curseforge.com/projects/recurrent-complex/files/2355742/download";
    "version" = "1.2.5.1";
    "title" = "Recurrent Complex";
    "projectID" = 223150;
    "filename" = "RecurrentComplex-1.2.5.1.jar";
    "dependencies" = [224535];
    "encoded" = "RecurrentComplex-1.2.5.1.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/recurrent-complex";
    "type" = "remote";
    "md5" = "28ad2e33c8b37014293946021fa02653";
  };
  "redstone-paste" = {
    "projectID" = 67508;
    "title" = "Redstone Paste";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/redstone-paste";
  };
  "refined-storage" = {
    "src" = "https://minecraft.curseforge.com/projects/refined-storage/files/2356149/download";
    "version" = "1.3.5";
    "title" = "Refined Storage";
    "projectID" = 243076;
    "filename" = "refinedstorage-1.3.5.jar";
    "dependencies" = [];
    "encoded" = "refinedstorage-1.3.5.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/refined-storage";
    "type" = "remote";
    "md5" = "802a7f5a515244500a7281dff6e6112d";
  };
  "refraction" = {
    "projectID" = 253578;
    "title" = "Refraction";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/refraction";
  };
  "reliquary" = {
    "projectID" = 59713;
    "title" = "Reliquary";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/reliquary";
  };
  "resource-loader" = {
    "src" = "https://minecraft.curseforge.com/projects/resource-loader/files/2350835/download";
    "version" = "1.11-1.5.1";
    "title" = "Resource Loader";
    "projectID" = 226447;
    "filename" = "ResourceLoader-MC1.11-1.5.1.jar";
    "dependencies" = [];
    "encoded" = "ResourceLoader-MC1.11-1.5.1.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/resource-loader";
    "type" = "remote";
    "md5" = "f6cc5da4f6ba788a7e17d68cb95052a2";
  };
  "shadowfacts-forgelin" = {
    "src" = "https://minecraft.curseforge.com/projects/shadowfacts-forgelin/files/2345526/download";
    "version" = "1.1.0";
    "title" = "Shadowfacts&#x27; Forgelin";
    "projectID" = 248453;
    "filename" = "Forgelin-1.1.0.jar";
    "dependencies" = [];
    "encoded" = "Forgelin-1.1.0.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/shadowfacts-forgelin";
    "type" = "remote";
    "md5" = "de67117970343f91760b4d0eef7685be";
  };
  "sleeping-bag" = {
    "projectID" = 244584;
    "title" = "Sleeping Bag";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/sleeping-bag";
  };
  "soul-shards-the-old-ways" = {
    "src" = "https://minecraft.curseforge.com/projects/soul-shards-the-old-ways/files/2347284/download";
    "version" = "1.11-2.6.6-47";
    "title" = "Soul Shards: The Old Ways";
    "projectID" = 226958;
    "filename" = "SoulShards-TOW-1.11-2.6.6-47.jar";
    "dependencies" = [];
    "encoded" = "SoulShards-TOW-1.11-2.6.6-47.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/soul-shards-the-old-ways";
    "type" = "remote";
    "md5" = "508d9a31ee553eb74eeb654e525107a0";
  };
  "sound-filters" = {
    "src" = "https://minecraft.curseforge.com/projects/sound-filters/files/2356332/download";
    "version" = "0.9_for_1.11";
    "title" = "Sound Filters";
    "projectID" = 222789;
    "filename" = "SoundFilters-0.9_for_1.11.jar";
    "dependencies" = [];
    "encoded" = "SoundFilters-0.9_for_1.11.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/sound-filters";
    "type" = "remote";
    "side" = "client";
    "md5" = "928b18e1a4286ee03c2bf631622cb4f7";
  };
  "steves-carts-reborn" = {
    "projectID" = 253462;
    "title" = "Steves Carts Reborn";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/steves-carts-reborn";
  };
  "super-circuit-maker" = {
    "projectID" = 248619;
    "title" = "Super Circuit Maker";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/super-circuit-maker";
  };
  "tesla" = {
    "src" = "https://minecraft.curseforge.com/projects/tesla/files/2347255/download";
    "version" = "1.11-1.3.0.51";
    "title" = "TESLA";
    "projectID" = 244651;
    "filename" = "Tesla-1.11-1.3.0.51.jar";
    "dependencies" = [];
    "encoded" = "Tesla-1.11-1.3.0.51.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/tesla";
    "type" = "remote";
    "md5" = "b8eaf270d59000b298be75ddac8411c5";
  };
  "the-spice-of-life" = {
    "projectID" = 220811;
    "title" = "The Spice of Life";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/the-spice-of-life";
  };
  "thutcore" = {
    "src" = "https://minecraft.curseforge.com/projects/thutcore/files/2353461/download";
    "version" = "4.3.1";
    "title" = "ThutCore";
    "projectID" = 224428;
    "filename" = "thutcore-4.3.1.jar";
    "dependencies" = [];
    "encoded" = "thutcore-4.3.1.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/thutcore";
    "type" = "remote";
    "md5" = "d1cf1147e713f4e1a3ae7d1a48f2f1fd";
  };
  "thuts-elevators" = {
    "src" = "https://minecraft.curseforge.com/projects/thuts-elevators/files/2353488/download";
    "version" = "5.0.0";
    "title" = "Thut&#x27;s Elevators";
    "projectID" = 224375;
    "filename" = "thuttech-5.0.0.jar";
    "dependencies" = [224428];
    "encoded" = "thuttech-5.0.0.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/thuts-elevators";
    "type" = "remote";
    "md5" = "87517539fca4069f60875ee3536cf9b1";
  };
  "tomb-many-graves" = {
    "projectID" = 245224;
    "title" = "Tomb Many Graves";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/tomb-many-graves";
  };
  "useless-deleter" = {
    "projectID" = 246832;
    "title" = "Useless Deleter";
    "type" = "missing";
    "projectPage" = "https://minecraft.curseforge.com/projects/useless-deleter";
  };
  "waddles" = {
    "src" = "https://minecraft.curseforge.com/projects/waddles/files/2346382/download";
    "version" = "1.11-0.5.1";
    "title" = "Waddles";
    "projectID" = 251767;
    "filename" = "Waddles-1.11-0.5.1.jar";
    "dependencies" = [];
    "encoded" = "Waddles-1.11-0.5.1.jar";
    "projectPage" = "https://minecraft.curseforge.com/projects/waddles";
    "type" = "remote";
    "md5" = "3bb97259cc58887e91b8f3a1488e3609";
  };
  "xaeros-minimap" = {
    "src" = ../bundled/xaeros-minimap/Xaeros_Minimap_1.11.8.1_Forge_1.10.2.jar;
    "filename" = "Xaeros_Minimap_1.11.8.1_Forge_1.10.2.jar";
    "version" = "1.11.8.1_Forge_1.10.2";
    "encoded" = "Xaeros_Minimap_1.11.8.1_Forge_1.10.2.jar";
    "type" = "local";
    "md5" = "0d92768284550c4965d8d091ae68ef7f";
  };
}
